version: '3.8'
services:
  api:
    image: viniciuspiresb/base-node-kubernetes
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/db"
      NODE_ENV: "development"
      PORT: 8000
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    ports:
      - "8000:8000"
  
  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
volumes:
  cache: